# Generated by Django 4.1.5 on 2023-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
